spring.application.name=CypherDB
spring.datasource.url=jdbc:postgresql://dpg-d36l7o7diees73bu9770-a:5432/cypherdb
spring.datasource.username=cypher_user
spring.datasource.password=onW9OGId0AyetcfeDMSFBSH5KfXbOF1Z
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
server.port=8081